collections:
  sections:
    output: false
  topics:
    output: true

defaults:
  - scope:
      path: "_sections/hiring/interviewing"
    values:
      topic: "interviewing"
  - scope:
      path: "_sections/proposals"
    values:
      topic: "proposal"
  